<template> 
    <div>
        <component v-bind:is="'style'" type="text/css">
            /*
            Stylesheet generated by
            Mechetle Mache
            */

            {{styles}}
        </component>

        <header>
            <div class="border-top-naturalize"></div>
            <Container id="header-wrapper" class="fluid">
                <GridX id="header-text">
                    <Cell class="large-9 post-details">
                        <div class="text-wrapper">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><NuxtLink to="/">Home</NuxtLink></li>
                                    <li class="breadcrumb-item active"><NuxtLink to="/portfolio">Portfolio</NuxtLink></li>
                                    <li class="breadcrumb-item active" aria-current="page">{{$route.params.project}}</li>
                                </ol>
                            </nav>
                            <h1>{{postShown.title}}</h1>
                        </div>
                    </Cell>
                </GridX>
                <GridX id="display-item-wrapper">
                    <Cell class="large-2" id="post-info">
                        <p id="date">{{date_finished}}</p>
                        
                        <template v-for="el in postShown.category">
                            <template v-if="el == 'uiux'">
                                <NuxtLink to="/portfolio/UIUX">
                                    <p>UI & UX</p>
                                </NuxtLink>
                            </template>

                            <template v-else-if="el == 'motion'">
                                <NuxtLink to="/portfolio/motion">
                                    <p>Motion design</p> 
                                </NuxtLink>
                            </template>

                            <template v-else-if="el == 'branding'">
                                <NuxtLink to="/portfolio/branding">
                                    <p>Misc.</p>
                                </NuxtLink>
                            </template>

                            <template v-else>
                                <NuxtLink to="/portfolio/motion">
                                    <p>Misc.</p>                                  
                                </NuxtLink>
                            </template>
                        </template>
                    </Cell>
                    <Cell id="display-item" class="large-10">
                        <!-- Video / header image goes here-->
                    </Cell>
                </GridX>
            </Container>
            <div id="header-background">
                <GridX>
                    <div id="post-details-bg" class="cell large-9">
                    </div>
                </GridX>
            </div>
            
            <!-- <div id="header-bg" class="header-post-image rellax" data-rellax-speed="-4">
                <div class="image-header">
                    <img :src="postShown.img" class="image-header-temp">
                </div>
                <div class="transition"></div>
            </div> -->
        </header>
        
        <main v-if="(postShown.oneByOne === false) || (postShown.oneByOne == null)" class="work-details wide-vid">
            <Container class="slim">
                <GridX class="grid-margin-x">
                    <Cell class="large-7 work-details">
                        <q>{{postShown.callout}}</q>
                        <p>{{postShown.desc}}</p>
                    </Cell>
                    <Cell class="large-5">
                        <div class="little-bits">
                            <div class="little-bits-cols">
                                <p>
                                    <b>Context of work:</b><br>
                                    {{postShown.design_context}}
                                </p>
                            </div>
                            <div class="little-bits-cols">
                                <p>
                                    <b>Client:</b><br>
                                    {{postShown.client}}
                                </p>
                                <p>
                                    <b>Client field:</b><br>
                                    {{postShown.client_field  == null ? "Not available" : postShown.client_field }}
                                </p>
                            </div>
                        </div>
                    </Cell>
                </GridX>
            </Container>

            <MacheGroup v-model:block="postShown.body.children" :path="-1">
            </MacheGroup>
        </main>

        <NerdyDetails
            :dimensions="dimensions"
            :exported="postShown.exported"
            :supplied="postShown.supplied"
            :datefinished="date_finished"
            >
        </NerdyDetails>
        
        <section id="up-next">
            <Container class="fluid">
                <GridX class="grid-margin-x">
                    <template v-if="similarPosts != null">
                        <WorkThumb 
                            :title="similarPosts.title" 
                            :slug="similarPosts.slug" 
                            :img-src="similarPosts.img + '?' + similarPosts.id" 
                            :desc="similarPosts.alt" 
                            :size="6">

                            <h2>
                                Somthing similar
                            </h2>
                        </WorkThumb>
                    </template>
                    
                    <template v-if="newerPost != null">
                        <WorkThumb 
                            :title="newerPost.title" 
                            :slug="newerPost.slug" 
                            :img-src="newerPost.img + '?' + newerPost.id" 
                            :desc="newerPost.alt" 
                            :size="6" 
                            :cat="newerPost.category">
                            
                            <h2>
                                Previous work
                            </h2>
                        </WorkThumb>
                    </template>
                </GridX>
            </Container>
        </section>
    </div>

</template>

<script>
export default {

    mounted() {
        var rellax = new Rellax('.rellax', {
            //center: true, causes issues
            vertical: true,
            horizontal: false
        });
    },

    methods: {
    }

}
</script>

<script setup>
const route = useRoute()

console.log("routed to...", route.params.project)
console.log(`/api/data/${route.params.project}`)

/* Fetching data of page */
const {data: postShown} = await useFetch(`/api/data?post=${route.params.project}`, { initialCache: false })

let dimensions = reactive({
    x:1080, 
    y:1080
})

/* console.log(postShown.value) */
//let tags = postShown.value.tags[0]
//let id = postShown.value._id

/* Nerdy details */
// Finished date:
let date = new Date(postShown.value.finishDate)
let date_finished = date.toLocaleDateString(
    "en-GB", 
    { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    }
)

const styles = computed(() => {
    let generatedStyles = "";
    console.log("Test:", postShown.value.style["group-2"].width)

    for (let key in postShown.value.style) {
        let props = "";

        let selectorStyle = postShown.value.style[key]
        for (let prop in selectorStyle) {
            props = props + `${prop.replace(/[A-Z]+(?![a-z])|[A-Z]/g, ($, ofs) => (ofs ? "-" : "") + $.toLowerCase())}: ${
                typeof selectorStyle[prop] == 'string' && selectorStyle[prop].length > 0 ?
                    selectorStyle[prop]
                    : selectorStyle[prop].length > 0 ?
                    selectorStyle[prop].join(' ')
                    : "initial"}`
            props = props + ";"
        };

        generatedStyles = generatedStyles + ` #${key} {${props}}`
    };

    console.log(generatedStyles)
    return generatedStyles
})

// Video dimensions
onMounted(() => {
    let video = document.querySelector("#actual-vid");
    try {
        video.addEventListener('loadeddata', function(event){
            dimensions.y = video.videoHeight;
            dimensions.x = video.videoWidth;
        });
    } catch (error) {
        console.log("There are no videos oof, won't do anything", error)
    }
    
})

/* After shown post: */
const {data: similarPostsUnparsed} = await useFetch(`/api/data?tags=${postShown.value.tags[0]}`)
const similarPosts = computed(() => {
    let randomNum = Math.floor(Math.random() * similarPostsUnparsed.value.length)
    return similarPostsUnparsed.value.filter(post => post.slug != postShown.slug)[randomNum]
})
const {data: newerPost} = await useFetch(`/api/data?prev=${postShown.value.slug}&limit=1`)

//console.log(this)
</script>

<style lang="scss" scoped>
    #post-info {
        margin-top: 37vh;
        p {
            margin: 0;
            font-weight: 700;
        }
    }

    q {
        font-size: 1.5rem;
        margin: 2em 0;
        position: relative;

        &::after {
            top: 0;
            left: -2em;
            content: "";
            position: absolute;
            height: 100%;
            width: 0.5em;
            background: linear-gradient(0deg, #D1E4FF 3.27%, rgb(255, 214, 244) 74.01%);
        }
    }

    header {
        background: none;
        height: 120vh;
        position: relative;
        padding-top: 2em;

        .grid-x {
            height: 100%;
        }

        #header-background {
            padding-top: 2.5em;
            position: absolute;
            top: 0;
            height: 100%;
            width: 100%;
            z-index: -1;
            margin-top: 7em;
            
            #post-details-bg {
                background: #FFD6F4;
                height: 65%;
                border-radius: 0px 0.75em 0.75em 0px;
            }
        }

        #display-item-wrapper {
            flex-grow: 1;
            margin-top: -2em;
        }
        
        #display-item {
            height: 100%;
            background: #001C38;
            border-radius: 0.75em;
        }

        #header-text {
            height: unset;
        }

        nav {
            padding: 0 0 2em;
        }

        #header-wrapper {
            height: 100%;
            display: flex;
            flex-direction: column;

            h1 {padding-right: 6.8rem;}
        }

        
        
        .fluid {
            padding-right: 6.8rem !important;
            padding-left: 6.8rem !important;
        }

        .breadcrumb {
            a, li {
                color: #390036;
            }
            .breadcrumb-item + .breadcrumb-item:hover::before {
                color: #191C1D;
            }
        }

        .text-wrapper {
            padding-left: 0;
            position: relative;
            color: #191C1D;
            margin-top: 12em;
            margin-bottom: 3em;
        }

        .border-top-naturalize {
            z-index: 1;
            background: #ffffff;
        }

        .border-bottom-naturalize {
            background: transparent;
        }

        #header-bg {
            position: absolute;
            top: 0;
            width: 100%;
            z-index: -1;
            height: unset;
        }

        .image-header{
            height: 80vh;
            background-size: cover;
            transform: scale(1.35);
            //filter: blur(60px);

            img {
                height: 1px;
                width: 1px;
            }
        }
        .nerdy-details {
            margin-right: -6.8rem;
            padding-right: 6.8rem;
        }
    

        .transition {
            background: #eceff1;
        }
    }

    .little-bits {
        display: flex;
        flex-wrap: nowrap;
        margin-top: 4em;
        margin-left: 5em;
        flex-direction: column;
        align-items: flex-end;
        color: #73777F;

        .little-bits-cols {
            width: 50%;

            &:last-child {
                padding-left: 3em;
            }
        }
    }

    .work-details {
        margin: 4em 0 15em;
    }

    .work-details.wide-vid {
        margin-bottom: 7em;
    }

    section#similar-work {
        padding-top: 0;
    }

    section#next-prev-work {
        //background: #eceff1;    // maybe no???
        padding-bottom: 5em;

        h2 {
            display: flex;
            // flex-direction: row;

            > span {
                font-family: inherit;

                &:first-of-type {
                    flex: none;
                }

                &:last-of-type {
                    width: 100%;
                    background: #0b233d;
                    margin-left: 0.5em;
                    height: 15px;
                    align-self: center;
                }
            }
        }
    }

    .go-explore {
        margin-top: 6em;
        margin-left: -4.5em;
        padding: 3em 4.5em;
        height: 60vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        background: #d81b60;
        color: #fff;
    }

    
</style>